name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  pages:
    name: Build gh-pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          VALIDATE_WEBIDL: false
          VALIDATE_MARKUP: false
